#!/usr/bin/env node
/**
 * Unit tests for SudokuPad link encoding.
 * These are reference links generated by SudokuPad itself.
 * Our encoder must produce output that decompresses to identical JSON.
 */

const LZString = require('./lz-string-custom.js');

const testCases = [
  {
    name: 'af6c with Enjoy!',
    url: 'N4IgDiBcIIIKICYCsAVAygSwGwAkVYDEAWAEQBsBxAZxgGEAzASQGYApBARRIHYArAWQAyWZgX4gANCAB2UEHACGVAJ4ACWmSVUMAY1UBtABwIAJlgX0sOgLqqAFFQAWCgE4BTEwEpJIKnJ8AtnJw0rwA9soAhCAAvkAAA==',
    json: '{"p":"AE25TSi6HT6F4DlGsACfI3J2QD7jML63FM","n":"Easy Classic [82d6af6c] (shared)","s":"","m":"Enjoy!"}'
  },
  {
    name: 'af6c with Enjoy!!',
    url: 'N4IgDiBcIIIKICYCsAVAygSwGwAkVYDEAWAEQBsBxAZxgGEAzASQGYApBARRIHYArAWQAyWZgX4gANCAB2UEHACGVAJ4ACWmSVUMAY1UBtABwIAJlgX0sOgLqqAFFQAWCgE4BTEwEpJIKnJ8AtnJw0rwA9soAhJEgAL5AA==',
    json: '{"p":"AE25TSi6HT6F4DlGsACfI3J2QD7jML63FM","n":"Easy Classic [82d6af6c] (shared)","s":"","m":"Enjoy!!"}'
  }
];

let passed = 0;
let failed = 0;

console.log('SudokuPad Encoding Unit Tests\n' + '='.repeat(40) + '\n');

for (const tc of testCases) {
  console.log(`Test: ${tc.name}`);
  
  // 1. Verify reference URL decompresses to expected JSON
  const decompressed = LZString.decompressFromBase64(tc.url);
  if (decompressed !== tc.json) {
    console.log('  ✗ FAIL: Reference URL does not decompress to expected JSON');
    console.log(`    Expected: ${tc.json}`);
    console.log(`    Got:      ${decompressed}`);
    failed++;
    continue;
  }
  
  // 2. Compress the JSON and verify it decompresses to same result
  const recompressed = LZString.compressToBase64(tc.json);
  const roundTrip = LZString.decompressFromBase64(recompressed);
  
  if (roundTrip !== tc.json) {
    console.log('  ✗ FAIL: Round-trip decompression mismatch');
    console.log(`    Expected: ${tc.json}`);
    console.log(`    Got:      ${roundTrip}`);
    failed++;
    continue;
  }
  
  // 3. Require exact match
  if (recompressed !== tc.url) {
    console.log('  ✗ FAIL: Output does not match reference URL');
    console.log(`    Expected: ${tc.url}`);
    console.log(`    Got:      ${recompressed}`);
    failed++;
    continue;
  }
  
  console.log('  ✓ PASS: Exact match');
  passed++;
}

console.log('\n' + '='.repeat(40));
console.log(`Results: ${passed} passed, ${failed} failed`);

process.exit(failed > 0 ? 1 : 0);
